import solanaConfig from '@solana-config/oxc/oxfmt';
import { defineConfig } from 'oxfmt';

export default defineConfig({
    ...solanaConfig,
    ignorePatterns: [
        // Build outputs (also gitignored).
        '**/dist/',
        '**/lib/',
        // Skills sources are managed upstream by the lorisleiva/skills tool;
        // local Oxfmt should not fight with whatever the sync produces.
        '.agents/',
        'skills-lock.json',
        // Changeset content is autogenerated by `changeset add` with its own
        // formatting; CI workflow PR template is intentionally hand-formatted.
        '.changeset/',
        '.github/workflows/PULL_REQUEST_TEMPLATE.md',
        // Autogenerated by changesets/action on release.
        'CHANGELOG.md',
    ],
});
